export const LOAD_PROFIL = "LOAD_PROFIL"
export const GET_PROFIL_SUCCESS = "GET_PROFIL_SUCCESS"
export const GET_PROFIL_FAIL = "GET_PROFIL_FAIL"
export const EDIT_PROFIL_FAIL = "EDIT_PROFIL_FAIL"
export const EDIT_PROFIL_SUCCESS = "EDIT_PROFIL_SUCCESS"

